version: '3.4'

services:
  gardenincbackend:
    image: gardenincbackend
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    links:
      - mongodb

  gardenincfrontend:
    image: gardenincfrontend
    build:
      context: ./frontend/GardenInc
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend/GardenInc:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - gardenincbackend

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongoData:/data/db